nodemodule error fixed

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch: # Manually deploy on the main branch
 
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
     container:
       image: node:16.14.0
@@ -26,16 +26,47 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Transfer all files directly including node_modules
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    container:
+      image: node:16.14.0
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install dependencies
+        run: npm ci # Ensure dependencies are installed locally
+
+      - name: Create .env file dynamically
+        run: |
+          echo "Creating .env file..."
+          case "${{ github.ref }}" in
+            "refs/heads/main")
+              echo "Deploying to production server (main branch)..."
+              echo "${{ secrets.ENV_FILE_CONTENT_PROD }}" > .env
+              ;;
+            "refs/heads/testing")
+              echo "Deploying to testing server (testing branch)..."
+              echo "${{ secrets.ENV_FILE_CONTENT_STAGE }}" > .env
+              ;;
+            *)
+              echo "Invalid branch. Exiting."
+              exit 1
+              ;;
+          esac
+
+      - name: Sync files directly including node_modules
         uses: SamKirkland/FTP-Deploy-Action@v4.2.0
         with:
           server: ftp.theshippinghack.com
           username: ${{ secrets.TESTING_FTP_USERNAME }}
           password: ${{ secrets.TESTING_FTP_PASSWORD }}
-          local-dir: ./ # Upload all files, including node_modules
+          local-dir: ./ # Upload everything including node_modules
           exclude: |
             .git*
-            .github* # Exclude CI/CD configuration files if not needed
+            .github*
+            .env # Optionally exclude the .env file after syncing
 
       - name: Verify deployment
         run: echo "Deployment completed successfully!"
